[2023-08-14T06:09:30.590+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.is_forex_rates_available manual__2023-08-14T06:09:29.792546+00:00 [queued]>
[2023-08-14T06:09:30.602+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.is_forex_rates_available manual__2023-08-14T06:09:29.792546+00:00 [queued]>
[2023-08-14T06:09:30.602+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-08-14T06:09:30.603+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-08-14T06:09:30.603+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-08-14T06:09:30.623+0000] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_forex_rates_available> on 2023-08-14 06:09:29.792546+00:00
[2023-08-14T06:09:30.629+0000] {standard_task_runner.py:55} INFO - Started process 2217 to run task
[2023-08-14T06:09:30.632+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'forex_data_pipeline', 'is_forex_rates_available', 'manual__2023-08-14T06:09:29.792546+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/forex_data_pipeline_v_1.py', '--cfg-path', '/tmp/tmp6dogdpit']
[2023-08-14T06:09:30.633+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask is_forex_rates_available
[2023-08-14T06:09:30.711+0000] {task_command.py:388} INFO - Running <TaskInstance: forex_data_pipeline.is_forex_rates_available manual__2023-08-14T06:09:29.792546+00:00 [running]> on host 7dfb041806a2
[2023-08-14T06:09:30.813+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@localhost.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=forex_data_pipeline
AIRFLOW_CTX_TASK_ID=is_forex_rates_available
AIRFLOW_CTX_EXECUTION_DATE=2023-08-14T06:09:29.792546+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-14T06:09:29.792546+00:00
[2023-08-14T06:09:30.814+0000] {http.py:122} INFO - Poking: marclamberti/f45f872dea4dfd3eaa015a4a1af4b39b
[2023-08-14T06:09:30.841+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 199, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 137, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 128, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 130, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 84, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `forex_api` isn't defined
[2023-08-14T06:09:30.847+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=forex_data_pipeline, task_id=is_forex_rates_available, execution_date=20230814T060929, start_date=20230814T060930, end_date=20230814T060930
[2023-08-14T06:09:30.863+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task is_forex_rates_available (The conn_id `forex_api` isn't defined; 2217)
[2023-08-14T06:09:30.884+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-08-14T06:09:30.918+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
