[2023-08-14T06:09:50.325+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_dag.fail scheduled__2023-08-10T00:00:00+00:00 [queued]>
[2023-08-14T06:09:50.336+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_dag.fail scheduled__2023-08-10T00:00:00+00:00 [queued]>
[2023-08-14T06:09:50.337+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-08-14T06:09:50.338+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-08-14T06:09:50.338+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-08-14T06:09:50.355+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): fail> on 2023-08-10 00:00:00+00:00
[2023-08-14T06:09:50.360+0000] {standard_task_runner.py:55} INFO - Started process 2285 to run task
[2023-08-14T06:09:50.364+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_dag', 'fail', 'scheduled__2023-08-10T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/data_dag.py', '--cfg-path', '/tmp/tmp7mep81ia']
[2023-08-14T06:09:50.365+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask fail
[2023-08-14T06:09:50.383+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:400: DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
  engine_args["encoding"] = conf.get("database", "SQL_ENGINE_ENCODING", fallback="utf-8")

[2023-08-14T06:09:50.439+0000] {task_command.py:388} INFO - Running <TaskInstance: data_dag.fail scheduled__2023-08-10T00:00:00+00:00 [running]> on host 7dfb041806a2
[2023-08-14T06:09:50.526+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_dag
AIRFLOW_CTX_TASK_ID=fail
AIRFLOW_CTX_EXECUTION_DATE=2023-08-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-10T00:00:00+00:00
[2023-08-14T06:09:50.528+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-14T06:09:50.529+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n                valid=10\n                if [ $(($valid % 2)) == 1 ]; then\n                        exit 1\n                else\n                        exit 0\n                fi\n            ']
[2023-08-14T06:09:50.539+0000] {subprocess.py:86} INFO - Output:
[2023-08-14T06:09:50.541+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-14T06:09:50.572+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=data_dag, task_id=fail, execution_date=20230810T000000, start_date=20230814T060950, end_date=20230814T060950
[2023-08-14T06:09:50.616+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-08-14T06:09:50.635+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
